version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ai-ft-ollama
    restart: unless-stopped
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    networks:
      - ai-ft-network
    environment:
      - OLLAMA_NUM_PARALLEL=2
      - OLLAMA_MAX_LOADED_MODELS=2
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

networks:
  ai-ft-network:
    external: true

volumes:
  ollama_data:
    driver: local